<a href="https://colab.research.google.com/github/luqadio/sample/blob/master/myproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Don't close this browser tab while your project is running.

**Run the code block below to start your Clouderizer project. **

In [0]:
!curl -s "https://console.clouderizer.com/givemeinitsh/IURpDyYu" | bash

Great! Your Clouderizer project is initializing...it might take few minutes before it is ready.

**************************************************************************************
YOU SHOULD NOW SWITCH BACK TO CLOUDERIZER WEB PAGE TO START WORKING ON YOUR PROJECT
**************************************************************************************


In [0]:
from __future__ import print_function
import numpy as np

data1 = [1, 2, 3, 4, 5]  # it is creating a list
arr1 = np.array(data1)   #its creating one dimentional arry from the created list(data1)
data2 = [range(1, 5), range(5, 9)]  # its creating a list with two-D list
arr2 = np.array(data2)  #its creating one dimentional arry from the created list(data3)
arr2.tolist() # converting the array to list


[[1, 2, 3, 4], [5, 6, 7, 8]]

In [0]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
# gives 2D array with 3 rows and 10 columns
np.zeros((3,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [0]:
np.ones(10) #Return a new array of ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
np.linspace(0,1,5) #Returns 5 values between 0-1 with evenly spaced interval

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [0]:
np.logspace(0,3,4) #Returns 5 values between 0-1 with linearly spaced interval

array([   1.,   10.,  100., 1000.])

In [0]:
int_array= np.arange(5)     #it creats an array from 0 to 4
int_array
float_array= int_array.astype(float) # it converts the created array type from int to float 
change_float
float_array

array([0., 1., 2., 3., 4.])

In [0]:
arr1.dtype #gives the datatype
arr2.dtype #gives the datatype

dtype('int64')

In [0]:
arr1.ndim #gives the dimension

1

In [0]:
arr2.size #gives the size

8

In [0]:
arr2.shape #gives the shape(number of row and column)

(2, 4)

In [0]:
len(arr2) #gives the total number of elements

2

In [0]:
arr= np.arange(10,dtype=float).reshape((2,5)) #arranges the number from 0-10 and the type is float and reshaping it into 2 rows and 5 coloums
arr

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [0]:
print(arr.reshape(5,2)) #it is used for reshaping the dimension of the array

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [0]:
a= np.array([0,1])
a_col= a[:,np.newaxis] #changes row into column
p
print(a_col)
a_col= a[:,None]

[[0]
 [1]]


In [0]:
arr_flt= arr.flatten() #flattens a array in 1D
arr_flt

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [0]:
a= np.array([0,1])
b=np.array([2,3])
ab= np.stack((a,b)) #stacks and transposes
print(ab)

[[0 1]
 [2 3]]


In [0]:
arr= np.arange(9, dtype=float).reshape((3,3))
print(arr)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [0]:
print(arr[0,2]) #prints the 2nd coloumn in the 0th row
print(arr[1][2]) #prints the 2nd coloumn in the 0th row

2.0
5.0


In [0]:
print(arr[0,:]) # it return row 0
print(arr[:,0]) # it return column 0
print(arr[:,:2]) # its printing the column befor index 2 
print(arr[0:2,1:]) # its printing first from 2nd column to the last 
print(arr[1:,:-1])  # it printing from row 1 to 4 reversing the column arraingment

[0. 1. 2.]
[0. 3. 6.]
[[3. 4.]
 [6. 7.]]
[[1. 2.]
 [4. 5.]]
[[3. 4.]
 [6. 7.]]


In [0]:
arr= np.arange(16).reshape(4,4) #shape the array to 4 by 4
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
arr[1:3,1:3] #slicing 1st and 2nd row of 1st and 2nd column  

array([[ 5,  6],
       [ 9, 10]])

In [0]:
my_arr= np.array([[1,2,3],[5,6,7]]) 
my_arr

array([[1, 2, 3],
       [5, 6, 7]])

In [0]:
a=np.array([1,2])
b=np.array([3,4])
ab= np.stack((a,b)).T #stacks and transposes
ab

array([[1, 3],
       [2, 4]])

In [0]:
arr[0,::-1] )#reversing the list of zeroth coloumn

array([3, 2, 1, 0])

In [0]:
arr_1= arr[arr>10] #checking if the valyes in array 1 is greater than five and prints it into a single list
arr_1 

In [0]:
names= np.array(['Bob','Janny','Herry','Joey']) 

In [0]:
names=='Bob'

array([ True, False, False, False])

In [0]:
(names == 'Bob')|(names== 'Joey')

array([ True, False, False,  True])

In [0]:
names[names!='Bob']

array(['Janny', 'Herry', 'Joey'], dtype='<U5')

In [0]:
names[names!='Bob']= 'Joey'
names

array(['Bob', 'Joey', 'Joey', 'Joey'], dtype='<U5')

In [0]:
np.unique(names)

array(['Bob', 'Joey'], dtype='<U5')

In [0]:
nums= np.arange(5)  # it will add the two array element wise
nums

array([0, 1, 2, 3, 4])

In [0]:
nums*10

array([ 0, 10, 20, 30, 40])

In [0]:
nums= np.sqrt(nums)
nums

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [0]:
np.ceil(nums)

array([0., 1., 2., 2., 2.])

In [0]:
np.isnan(nums)

array([False, False, False, False, False])

In [0]:
nums+np.arange(5)

array([0.        , 2.        , 3.41421356, 4.73205081, 6.        ])

In [0]:
np.ceil(nums)

array([0., 1., 2., 2., 2.])

In [0]:
np.maximum(nums,np.array([1,-2,3,-4,5]))

array([1.        , 1.        , 3.        , 1.73205081, 5.        ])

In [0]:
vec1=np.random.randn(10)
vec1

array([-0.97413155,  0.9492524 ,  0.98877408, -0.73666721,  0.72037296,
        0.51883917,  0.06324399, -1.12876748,  0.56261509,  0.16592566])

In [0]:
vec2=np.random.randn(10)
vec2

array([-0.97112017, -0.17502679, -1.01487049,  0.38480384,  0.66004436,
       -1.16392715,  1.54035836, -0.63804146, -0.07620413,  0.28404346])

In [0]:
np.sqrt(np.sum((vec1-vec2)**2))

3.4951916066032367

In [0]:
rnd= np.random.randn(4,2)
rnd

array([[-1.16617841, -0.37895435],
       [ 0.29271618, -1.28853118],
       [-1.19895837,  1.40694396],
       [-0.90541268, -2.32816739]])

In [0]:
rnd.mean()

-0.6958177793736349

In [0]:
rnd.std()

1.0626266274627485

In [0]:
rnd.argmin()

7

In [0]:
rnd.sum(axis=0)

array([-2.97783328, -2.58870896])

In [0]:
rnd.sum(axis=1)

array([-1.54513276, -0.995815  ,  0.20798559, -3.23358007])

In [0]:
(rnd>0).sum()

2

In [0]:
(rnd>0).any()

True

In [0]:
(rnd>0).all()

False

In [0]:
np.random.seed(12233)
np.random.rand(2,3)

array([[0.05365932, 0.5235968 , 0.29504019],
       [0.91849674, 0.38277192, 0.74727789]])

In [0]:
np.random.randn(10) 

array([-0.90916109, -0.56930955,  1.14157433, -2.3529997 , -0.58003993,
        0.48227429, -0.77438052, -0.27171243,  0.98577908, -1.54014205])

In [0]:
np.random.randint(0,100,10) # return an array of 10 elements in range 0 to 100 randomly

array([66, 18, 67, 46, 39, 62, 18, 40, 98, 49])

In [0]:
a=np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]]) # add 2D with 1D array will make a array of bigger size of array
b=np.array([0,1,2])   # 1D array
a+b  # give output with addeding elements of 1D array and 2D array

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [0]:
X= np.random.randn(4,2)  # Array of given paramenter size with random values
X

array([[-0.23821285, -0.32263062],
       [-1.09940501, -1.96849306],
       [-0.23409331, -1.25442909],
       [ 0.57297594,  0.88439849]])

In [0]:
min_va= X.min(axis=0)
min_in=np.where(X.min(axis=0))
min_in

(array([0, 1]),)

In [0]:
def standarized(X):      
    x_norm= (X-np.mean(X))/np.std(X)
    return x_norm

xx=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(xx)
standarized(xx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

Explanation about what is happening on page 7

It explains the way how to add different dimensional arrays. for instance , we can add only same dimentional array. We cannot add 3 dimentinal with another 1dimentinal array. To add, 1d array with 3d, we must need to convert 1d array to 3d array. In the first picture it adds 3d array with another 3d array, In the second picture it adds 3d array with 1d array after that it convertng the 1d arry in to the 3d array. In the third picture, both were 1d array and so it converted both into 3d array first. finally, the output is same 3d array.
